# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-20 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('project_type', models.CharField(choices=[('RD', '\u7814\u53d1'), ('P', '\u9879\u76ee')], max_length=2)),
                ('project_date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=300)),
                ('p_id', models.CharField(blank=True, max_length=30)),
                ('bioinfo_people', models.ManyToManyField(related_name='bioinfo_staff', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lab_people', models.ManyToManyField(related_name='lab_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('species', models.CharField(choices=[('human', 'human'), ('mouse', 'mouse'), ('human_mouse', 'human_mouse'), ('other', 'other')], max_length=20)),
                ('sample_date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=300)),
                ('library_id', models.CharField(blank=True, max_length=80)),
                ('library_type', models.CharField(blank=True, choices=[('scRNA_SCOPE', 'scRNA_SCOPE'), ('scRNA_10X', 'scRNA_10X'), ('RNA_Seq', 'RNA_Seq'), ('WES', 'WES')], max_length=20)),
                ('AATI', models.ImageField(blank=True, upload_to='SGRNJ/Database/test/1.11/lab_project/media/AATI')),
                ('report', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_project', to='lab.Project')),
            ],
        ),
    ]
