# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-21 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('RD', '\u7814\u53d1'), ('P', '\u9879\u76ee')], max_length=2, verbose_name='type'),
        ),
    ]
