# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-26 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20181221_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='xiaji',
            field=models.BooleanField(default=True),
        ),
    ]
