# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-27 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_sample_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.TextField(),
        ),
    ]
