# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-16 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('RD', '\u7814\u53d1'), ('p', '\u9879\u76ee')], max_length=2),
        ),
    ]
