# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-26 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20181226_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='xiaji',
            field=models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False),
        ),
    ]
