# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20181227_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='need_analysis',
            field=models.BooleanField(default=False, verbose_name='\u5206\u6790\u9700\u6c42'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
