# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-16 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20181216_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='report',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sample',
            name='library_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
