# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-16 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20181216_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='report',
            field=models.FilePathField(blank=True),
        ),
    ]
