# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-29 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20181229_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='need_analysis',
        ),
        migrations.AddField(
            model_name='sample',
            name='xiaji',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e0b\u673a'),
        ),
    ]
