# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-16 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20181216_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='ImageField',
            field=models.ImageField(blank=True, upload_to='AATI'),
        ),
    ]
