# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-17 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_auto_20181216_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='report',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
