# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 01:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_auto_20181217_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='AATI',
            field=models.ImageField(blank=True, upload_to='AATI', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
    ]
