# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_auto_20181219_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='AATI',
            field=models.ImageField(blank=True, upload_to='AATI'),
        ),
    ]
