# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-19 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='people',
            field=models.ManyToManyField(to='lab.Employee'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='people',
            field=models.ManyToManyField(to='lab.Employee'),
        ),
    ]
