# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-19 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_auto_20181219_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='bioinfo_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='lab_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='people',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='people',
        ),
        migrations.AddField(
            model_name='project',
            name='bioinfo_staff',
            field=models.ManyToManyField(to='lab.bioinfo_staff'),
        ),
        migrations.AddField(
            model_name='project',
            name='lab_staff',
            field=models.ManyToManyField(to='lab.lab_staff'),
        ),
        migrations.AddField(
            model_name='sample',
            name='bioinfo_staff',
            field=models.ManyToManyField(to='lab.bioinfo_staff'),
        ),
        migrations.AddField(
            model_name='sample',
            name='lab_staff',
            field=models.ManyToManyField(to='lab.lab_staff'),
        ),
    ]
