# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-19 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0027_auto_20181219_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioinfo_staff',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='lab_staff',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bioinfo_staff',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lab_staff',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='bioinfo_staff',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='lab_staff',
        ),
        migrations.AddField(
            model_name='project',
            name='people',
            field=models.ManyToManyField(to='lab.Employee'),
        ),
        migrations.AddField(
            model_name='sample',
            name='people',
            field=models.ManyToManyField(to='lab.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('lab', '\u5b9e\u9a8c'), ('bioinfo', '\u751f\u4fe1'), ('administration', '\u884c\u653f')], max_length=30),
        ),
        migrations.DeleteModel(
            name='bioinfo_staff',
        ),
        migrations.DeleteModel(
            name='lab_staff',
        ),
    ]
