# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0031_auto_20181219_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('lab', '\u5b9e\u9a8c'), ('bioinfo', '\u751f\u4fe1'), ('xingzheng', '\u884c\u653f')], max_length=30, verbose_name='\u90e8\u95e8'),
        ),
    ]
