# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-20 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0032_auto_20181219_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('lab', '\u5b9e\u9a8c'), ('bioinfo', '\u751f\u4fe1'), ('xingzheng', '\u884c\u653f'), ('manage', '\u7ba1\u7406')], max_length=30, verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('RD', '\u7814\u53d1'), ('P', '\u9879\u76ee')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sample',
            name='species',
            field=models.CharField(choices=[('hm', 'human'), ('mm', 'mouse'), ('hm_mm', 'human_mouse'), ('other', 'other')], max_length=20),
        ),
    ]
