# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-20 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0035_auto_20181220_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='library_type',
            field=models.CharField(blank=True, choices=[('scRNA_SCOPE', 'scRNA_SCOPE'), ('scRNA_10X', 'scRNA_10X'), ('RNA_Seq', 'RNA_Seq'), ('WES', 'WES')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='species',
            field=models.CharField(choices=[('human', 'human'), ('mouse', 'mouse'), ('human_mouse', 'human_mouse'), ('other', 'other')], max_length=20),
        ),
    ]
