# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-20 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0036_auto_20181220_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_id',
            new_name='p_id',
        ),
    ]
