# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-24 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('paper', models.FileField(upload_to='SGRNJ/Database/test/1.11/lab_project/media/paper')),
                ('paper_people', models.ManyToManyField(related_name='paper_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
