# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-24 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_auto_20181224_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='submit1',
            field=models.FileField(blank=True, upload_to='SGRNJ/Database/test/1.11/lab_project/media/paper/submit'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='submit2',
            field=models.FileField(blank=True, upload_to='SGRNJ/Database/test/1.11/lab_project/media/paper/submit'),
        ),
    ]
